/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiToolsRouteImport } from './routes/ai-tools'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as DataCenterRouteImport } from './routes/data-center'
import { Route as DetailsRouteImport } from './routes/details'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FoldersRouteImport } from './routes/folders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiToolsRoute = AiToolsRouteImport.update({
  id: '/ai-tools',
  path: '/ai-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const DataCenterRoute = DataCenterRouteImport.update({
  id: '/data-center',
  path: '/data-center',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailsRoute = DetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FoldersRoute = FoldersRouteImport.update({
  id: '/folders',
  path: '/folders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-tools': typeof AiToolsRoute
  '/cases': typeof CasesRoute
  '/connect': typeof ConnectRoute
  '/data-center': typeof DataCenterRoute
  '/details': typeof DetailsRoute
  '/explore': typeof ExploreRoute
  '/folders': typeof FoldersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-tools': typeof AiToolsRoute
  '/cases': typeof CasesRoute
  '/connect': typeof ConnectRoute
  '/data-center': typeof DataCenterRoute
  '/details': typeof DetailsRoute
  '/explore': typeof ExploreRoute
  '/folders': typeof FoldersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-tools': typeof AiToolsRoute
  '/cases': typeof CasesRoute
  '/connect': typeof ConnectRoute
  '/data-center': typeof DataCenterRoute
  '/details': typeof DetailsRoute
  '/explore': typeof ExploreRoute
  '/folders': typeof FoldersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-tools'
    | '/cases'
    | '/connect'
    | '/data-center'
    | '/details'
    | '/explore'
    | '/folders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-tools'
    | '/cases'
    | '/connect'
    | '/data-center'
    | '/details'
    | '/explore'
    | '/folders'
  id:
    | '__root__'
    | '/'
    | '/ai-tools'
    | '/cases'
    | '/connect'
    | '/data-center'
    | '/details'
    | '/explore'
    | '/folders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiToolsRoute: typeof AiToolsRoute
  CasesRoute: typeof CasesRoute
  ConnectRoute: typeof ConnectRoute
  DataCenterRoute: typeof DataCenterRoute
  DetailsRoute: typeof DetailsRoute
  ExploreRoute: typeof ExploreRoute
  FoldersRoute: typeof FoldersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-tools': {
      id: '/ai-tools'
      path: '/ai-tools'
      fullPath: '/ai-tools'
      preLoaderRoute: typeof AiToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-center': {
      id: '/data-center'
      path: '/data-center'
      fullPath: '/data-center'
      preLoaderRoute: typeof DataCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/details': {
      id: '/details'
      path: '/details'
      fullPath: '/details'
      preLoaderRoute: typeof DetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folders': {
      id: '/folders'
      path: '/folders'
      fullPath: '/folders'
      preLoaderRoute: typeof FoldersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiToolsRoute: AiToolsRoute,
  CasesRoute: CasesRoute,
  ConnectRoute: ConnectRoute,
  DataCenterRoute: DataCenterRoute,
  DetailsRoute: DetailsRoute,
  ExploreRoute: ExploreRoute,
  FoldersRoute: FoldersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
